### ISSUE TITLE
System.Runtime.InteropServices.SEHException

### ISSUE THREAD

**Issue by ByErdem** [cefsharp/CefSharp#2716]
Hello Alex,
How are you? I downloaded CefSharp library from here for understand this and I tried. But I getting some errors. I guess, these are version based errors. Is there any errorless version?

Where the error occurred:
cef_string_wrappers.h: 222

https://drive.google.com/open?id=102Dwsk6q36IH99S5ynnkifiP9rHoFDaj

**Comment by amaitland** [comment]
Please fill out the bug report template. Please don't post an image of an exception, please read http://idownvotedbecau.se/imageofanexception/

**Comment by angshuman-agarwal** [comment]
@amaitland 
I am also getting the same exception. This is happening after I upgraded from 63.0.3 to [71.0.2](https://github.com/cefsharp/CefSharp/releases/tag/v71.0.2).
Apologies, it is not reproducible consistently, very random & not able to provide much more information at the moment, but trying to figure out.

In the meantime, this is the callstack (if that could give some hint) : Tried to lookup the [Error code](https://docs.microsoft.com/en-gb/windows/desktop/SecCrypto/common-hresult-values) - says `E_FAIL`

```
System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at CefBrowserHost.CreateBrowser(CefWindowInfo* , scoped_refptr<CefClient>* , CefStringBase<CefStringTraitsUTF16>* , CefStructBase<CefBrowserSettingsTraits>* , scoped_refptr<CefRequestContext>* )
   at CefSharp.ManagedCefBrowserAdapter.CreateBrowser(IWindowInfo windowInfo, BrowserSettings browserSettings, RequestContext requestContext, String address) in c:\projects\cefsharp\cefsharp.core\managedcefbrowseradapter.cpp:line 33
   at CefSharp.Wpf.ChromiumWebBrowser.CreateOffscreenBrowser(Size size) in C:\projects\cefsharp\CefSharp.Wpf\ChromiumWebBrowser.cs:line 1755
   at CefSharp.Wpf.ChromiumWebBrowser.OnActualSizeChanged(Object sender, SizeChangedEventArgs e) in C:\projects\cefsharp\CefSharp.Wpf\ChromiumWebBrowser.cs:line 1824
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.FrameworkElement.OnRenderSizeChanged(SizeChangedInfo sizeInfo)
   at System.Windows.ContextLayoutManager.fireSizeChangedEvents()
   at System.Windows.ContextLayoutManager.UpdateLayout()
   at System.Windows.Interop.HwndSource.SetLayoutSize()
   at System.Windows.Interop.HwndSource.set_RootVisualInternal(Visual value)
   at System.Windows.Window.SetRootVisual()
   at System.Windows.Window.SetRootVisualAndUpdateSTC()
   at System.Windows.Window.SetupInitialState(Double requestedTop, Double requestedLeft, Double requestedWidth, Double requestedHeight)
   at System.Windows.Window.CreateSourceWindow(Boolean duringShow)
   at System.Windows.Window.ShowHelper(Object booleanBox)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by amaitland** [comment]
@angshuman-agarwal Thanks,  please also fill out as much of the bug report as you can.

**Comment by angshuman-agarwal** [comment]
### Bug Report
- **What version of the product are you using?**
v71.0.2 via NuGet
https://www.nuget.org/packages/CefSharp.Wpf/71.0.2

- **What architecture x86 or x64?**
x64

- **On what operating system?**
Win7, Version 6.1 Build 7601:Service Pack 1

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
WPF

- **What steps will reproduce the problem?**
Unfortunately, it is very random. Not reproducible. STarted happening after upgrading from v63.0.3

- **What is the expected output? What do you see instead?**
Web Page should load without exceptions. But, `SEHException` is thrown randomly when webpage loads. But, even after the exception, web page does loads.


- **Please provide any additional information below.**

```
System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at CefBrowserHost.CreateBrowser(CefWindowInfo* , scoped_refptr<CefClient>* , CefStringBase<CefStringTraitsUTF16>* , CefStructBase<CefBrowserSettingsTraits>* , scoped_refptr<CefRequestContext>* )
   at CefSharp.ManagedCefBrowserAdapter.CreateBrowser(IWindowInfo windowInfo, BrowserSettings browserSettings, RequestContext requestContext, String address) in c:\projects\cefsharp\cefsharp.core\managedcefbrowseradapter.cpp:line 33
   at CefSharp.Wpf.ChromiumWebBrowser.CreateOffscreenBrowser(Size size) in C:\projects\cefsharp\CefSharp.Wpf\ChromiumWebBrowser.cs:line 1755
   at CefSharp.Wpf.ChromiumWebBrowser.OnActualSizeChanged(Object sender, SizeChangedEventArgs e) in C:\projects\cefsharp\CefSharp.Wpf\ChromiumWebBrowser.cs:line 1824
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.FrameworkElement.OnRenderSizeChanged(SizeChangedInfo sizeInfo)
   at System.Windows.ContextLayoutManager.fireSizeChangedEvents()
   at System.Windows.ContextLayoutManager.UpdateLayout()
   at System.Windows.Interop.HwndSource.SetLayoutSize()
   at System.Windows.Interop.HwndSource.set_RootVisualInternal(Visual value)
   at System.Windows.Window.SetRootVisual()
   at System.Windows.Window.SetRootVisualAndUpdateSTC()
   at System.Windows.Window.SetupInitialState(Double requestedTop, Double requestedLeft, Double requestedWidth, Double requestedHeight)
   at System.Windows.Window.CreateSourceWindow(Boolean duringShow)
   at System.Windows.Window.ShowHelper(Object booleanBox)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

*And, noticed this in Windows Event Viewer Application logs Window:*

```
Faulting application name: CefSharp.BrowserSubprocess.exe, version: 71.0.2.0, time stamp: 0x5c8355fb
Faulting module name: KERNELBASE.dll, version: 6.1.7601.24387, time stamp: 0x5c7f3ad8
Exception code: 0xe0434352
Fault offset: 0x000000000000be0d
Faulting process id: 0x159c
Faulting application start time: 0x01d4eca9ab27b7a7
Faulting application path: C:\source\Source\Bin\Debug\CefSharp.BrowserSubprocess.exe
Faulting module path: C:\Windows\system32\KERNELBASE.dll
Report Id: ebdc9d06-589c-11e9-8a7a-64006a7d07f4
```

- Does the cef log provide any relevant information? (By default there should be a debug.log file in your bin directory)
_Noticed only this error line in the debug.log_ 
`ERROR:gpu_process_transport_factory.cc(990)] Lost UI shared context.`

	
- Any other background information that's relevant? Are you doing something out of the ordinary? 3rd party controls?
N/A	

- **Does this problem also occur in the `CEF` Sample Application from http://opensource.spotify.com/cefbuilds/index.html?**
N/A

**Comment by ByErdem** [comment]
Hello Alex, First I apologize for my sharing. I wasn't know your work style. Our work style a little different at our country. I'm gonna try to fit with your work style. Please don't be prejudice to me. Also my English not good very well. I'm having a little hard time trying to explain the problem. I hope you understand me.

**Comment by amaitland** [comment]
@angshuman-agarwal Thanks for filling out the bug report 👍 

> * **On what operating system?**
>   Win7, Version 6.1 Build 7601:Service Pack 1

Does it crash on `Windows 10`?

> * Unfortunately, it is very random. Not reproducible. Started happening after upgrading from v63.0.3

How many machines are you seeing this on? Are they all running the same hardware?

> * _Noticed this error line in the debug.log_ (but, not sure it is related or not) - Matched the timestamp roughly.
>   `[0406/195113.071:ERROR:gpu_process_transport_factory.cc(990)] Lost UI shared context.`

Somewhat indicates that your `GPU Process` is crashing. Though it's not really definitive.

**Comment by angshuman-agarwal** [comment]
@amaitland  Thank you for coming back.

> Does it crash on `Windows 10`?

I am not able to comment on that because my environment is `Windows 7`

> How many machines are you seeing this on? Are they all running the same hardware?

Currently, only on my machine as I am developing & testing it out. All machines on which it will eventually get deployed are also Windows 7 and will have pretty much same hardware as mine.

> Somewhat indicates that your GPU Process is crashing. Though it's not really definitive.

Yes; but, until v63, everything was alright. I just did NuGet update alongwith VC++ 2015 libs. Did not have to change any code drastically. 

I will continue to ticker. Is there a document on how to debug through using the CEF Browser sub-process ? Maybe I can set that up on my machine to debug the native lib (`libcef`) ?

**Comment by amaitland** [comment]
> Yes; but, until v63, everything was alright. I just did NuGet update alongwith VC++ 2015 libs. Did not have to change any code drastically.

A **LOT** has changed in `Chromium`, you've jumped 8 versions ahead. 



> I will continue to analyse. Is there a document on how to debug using the CEF Browser sub-process in Visual Studio ? Maybe I can set that up on my machine to debug the native lib (`libcef`) ?

See https://github.com/cefsharp/CefSharp/wiki/Trouble-Shooting#unmanaged-crashes-when-the-process-dies

I'd probably start with just disabling `GPU Acceleration` and see if that makes a difference.

**Comment by angshuman-agarwal** [comment]
> I'd probably start with just disabling GPU Acceleration and see if that makes a difference.


Thanks. Is this what you are referring -https://cefsharp.github.io/api/63.0.0/html/M_CefSharp_CefSettings_DisableGpuAcceleration.htm

**Comment by amaitland** [comment]
> Is this what you are referring -https://cefsharp.github.io/api/63.0.0/html/M_CefSharp_CefSettings_DisableGpuAcceleration.htm

Yes, that will work.

Also I've just released the `73.1.120-pre01` packages. You can try with a newer version.

**Comment by angshuman-agarwal** [comment]
> Yes, that will work.

I did disable GPU as stated above. But, I am still getting this error in `debug.log`

`[0415/143619.899:ERROR:gpu_process_transport_factory.cc(990)] Lost UI shared context.`

**Comment by angshuman-agarwal** [comment]
@amaitland 

**Additional info:**
This happens when there is a small `1px Browser` inside a Window and when that window loads, it attempts to create instance of that 1px Browser & it crashes. If I do 20-30 times F5 from VS, this might happen once. At this point, I do not have the CefSharp Browser SubProcess & I can confirm that. So, I cannot attach and get a detailed native stack trace (using `libcef.dll.pdb`).

```
<cef:ChromiumWebBrowser x:Name="browser" Width="1" Height="1"/>
```

But, I enabled `gitlink`, and I see it crashes in:

```
CefSharp.Core.dll!<Unknown function> Line 33	C++
 	CefSharp.Wpf.dll!CefSharp.Wpf.ChromiumWebBrowser.CreateOffscreenBrowser(System.Windows.Size size) Line 1755	C#
 	CefSharp.Wpf.dll!CefSharp.Wpf.ChromiumWebBrowser.OnActualSizeChanged(object sender, System.Windows.SizeChangedEventArgs e) Line 1824	C#
```

`Line 33` in the callstack indicates the method being called by this function inside `ManagedCefBrowserAdapter.cpp` (which is a native call and since I do not have the Browser sub process, I cannot proceed further)- 

```
 if (!CefBrowserHost::CreateBrowser(*cefWindowInfoWrapper->GetWindowInfo(), _clientAdapter.get(), addressNative,
        *browserSettings->_browserSettings, static_cast<CefRefPtr<CefRequestContext>>(requestContext)))
    {
        throw gcnew InvalidOperationException("CefBrowserHost::CreateBrowser call failed, review the CEF log file for more details.");
    }
```

**Comment by amaitland** [comment]
@angshuman-agarwal Did you test with v73.1.120-pre01? Many bugs in the CEF OSR implementation have been fixed recently. I would also suggest you create the browser with more realistic dimensions, try like 640x480 or something much larger than 1x1.

Remove SetOffScreenRenderingBestPerformanceArgs() also and run your tests again. The browser subprocess running won't have any bearing on your ability to capture a call stack for the main process,  make sure you have native code debugging enabled in visual studio. 

As it only happens randomly it's unlikely a bug in CefSharp,  if it was a bug in CefSharp it should be reliably reproducible. 

For me to look into this any further I will require an example that reproduces the problem and an exact list of steps required. By all means continue debugging on your own.

**Comment by angshuman-agarwal** [comment]
> Did you test with v73.1.120-pre01?

Not yet

> I would also suggest you create the browser with more realistic dimensions, try like 640x480 or something much larger than 1x1.

I cannot, as I am using this browser size for a reason in my App and it has been fine in prior versions including `v63`

> Remove SetOffScreenRenderingBestPerformanceArgs() also and run your tests again.

Will do that 

> make sure you have native code debugging enabled in visual studio.

Thanks, will do

> For me to look into this any further I will require an example that `reproduces` the problem and an `exact` list of steps required.

Well, if only I could get that. Hence, I mentioned once in 25-30 times.

**Comment by amaitland** [comment]
For the purpose of debugging you should test with a realistic size, if a larger size works this is likely useful debugging information, doesn't matter if you use this for real in your app.

What was the last version this worked successfully in? You can quite easily take the branch for that version,  upgrade to the same version of CEF then perform your tests. Test with a newer version first.

**Comment by angshuman-agarwal** [comment]
> What was the last version this worked successfully in?

`v63.0.3`

**Comment by angshuman-agarwal** [comment]
> Remove SetOffScreenRenderingBestPerformanceArgs() also and run your tests again.

Out of curiosity, why do you say so ? I mean, you must have thought something here related to `ERROR:gpu_process_transport_factory.cc(990)` ?

**Comment by amaitland** [comment]
Version 69 and 71 both have bugs in the OSR rendering implementation  (CEF bugs) that have only been fixed in version 73.

I suggested disabling the gpu,  using SetOffScreenRenderingBestPerformanceArgs() adds two other commands, one of which is no longer relevant and shouldn't be used.  The method should be removed as it's implementation is based on outdated advice.

**Comment by angshuman-agarwal** [comment]
Ok, Thank you. Will follow one by one.

Firstly, 
> I suggested disabling the gpu

Removed `SetOffScreenRenderingBestPerformanceArgs1 and added this instead `cefs.DisableGpuAcceleration();`

I still got this in `debug.log`
`[0430/102251.586:ERROR:gpu_process_transport_factory.cc(990)] Lost UI shared context.`

But, as you suggested, will keep this change.

**Comment by amaitland** [comment]
If it makes no difference then leave GPU acceleration enabled is perfectly fine. Try loading chrome://gpu in your browser instance if upgrading doesn't work. Then compare to chrome

**Comment by angshuman-agarwal** [comment]
> leave GPU acceleration enabled is perfectly fine

I am still on `v71`, now `left GPU acceleration enabled`, error is not seen in `debug.log`. I also compared `chrome://gpu`. Thank you !!

I see nothing alarmingly different. Pretty much matches with actual Chrome. 
(my actual Google chrome version is `Chrome/72.0.3626.121`)

`Graphics Feature Status`, `Driver Bug Workarounds`, `Problems Detected` all match.

Now, I will see if I can reproduce the `SEHException` issue with this setting. If, still yes, then I will **upgrade** to version `pre-73` else leave it.

**Comment by angshuman-agarwal** [comment]
@amaitland  - Have been _incessantly_ trying to reproduce after the GPU acceleration enabling. Got tough to reproduce. But, managed now  & I see this in `debug.log`. (with `v71`)
Any hints here ?

```
[0430/152357.705:ERROR:gl_surface_egl.cc(537)] EGL Driver message (Error) eglCreateWindowSurface: Bad native window.
[0430/152357.705:ERROR:gl_surface_egl.cc(1068)] eglCreateWindowSurface failed with error EGL_BAD_NATIVE_WINDOW
[0430/152357.705:ERROR:gles2_command_buffer_stub.cc(223)] ContextResult::kSurfaceFailure: Failed to create surface.
```

**Comment by krptodr** [comment]
I wanted to add that I get this error:

>  An exception of type 'System.Runtime.InteropServices.SEHException' occurred in CefSharp.Core.dll and wasn't handled before a managed/native boundary
> 
> Additional information: External component has thrown an exception.

   

> at cef_string_utf8_to_utf16(SByte* , UInt32 , _cef_string_utf16_t* )
>    at CefStringTraitsUTF16.from_string(basic_string<char\,std::char_traits<char>\,std::allocator<char> >* str, _cef_string_utf16_t* s) in f:\programming\github\cefsharp\packages\cef.sdk.74.1.13\cef\include\internal\cef_string_wrappers.h:line 223
>    at CefStringBase<CefStringTraitsUTF16>.FromString(CefStringBase<CefStringTraitsUTF16>* , basic_string<char\,std::char_traits<char>\,std::allocator<char> >* str) in f:\programming\github\cefsharp\packages\cef.sdk.74.1.13\cef\include\internal\cef_string_wrappers.h:line 579
>    at CefStringBase<CefStringTraitsUTF16>.{ctor}(CefStringBase<CefStringTraitsUTF16>* , SByte* src) in f:\programming\github\cefsharp\packages\cef.sdk.74.1.13\cef\include\internal\cef_string_wrappers.h:line 316
>    at ?A0x247141ed.??__E?A0x247141ed@kEvaluateJavascriptRequest@Messaging@Internals@CefSharp@@YMXXZ() in f:\programming\github\cefsharp\cefsharp.core\internals\messaging\messages.h:line 18
>    at _initterm_m((fnptr)* pfbegin, (fnptr)* pfend) in f:\dd\vctools\crt\crtw32\msilcrt\puremsilcode.cpp:line 214
>    at <CrtImplementationDetails>.LanguageSupport.InitializePerProcess(LanguageSupport* ) in f:\dd\vctools\crt\crtw32\msilcrt\mstartup.cpp:line 380
>    at <CrtImplementationDetails>.LanguageSupport._Initialize(LanguageSupport* ) in f:\dd\vctools\crt\crtw32\msilcrt\mstartup.cpp:line 598
>    at <CrtImplementationDetails>.LanguageSupport.Initialize(LanguageSupport* ) in f:\dd\vctools\crt\crtw32\msilcrt\mstartup.cpp:line 804


My implementation is very basic. I created a win32 winform project with the following code:

`Imports CefSharp.Example
Imports CefSharp.WinForms

Public Class Form1
    Private Sub Form1_DragDrop(sender As Object, e As DragEventArgs) Handles Me.DragDrop

    End Sub

    Private Sub Form1_DragEnter(sender As Object, e As DragEventArgs) Handles Me.DragEnter

    End Sub

    Private Sub Form1_Load(sender As Object, e As EventArgs) Handles MyBase.Load
        Dim browser As ChromiumWebBrowser = New ChromiumWebBrowser("http://google.com")

    End Sub
End Class
`

**Comment by angshuman-agarwal** [comment]
I have tested in `73.1.130`, and, so far, I **did not** observe the error I reported earlier with `v71`.

**Comment by krptodr** [comment]
@angshuman-agarwal My implementation was using the latest version: 74.1.3

**Comment by amaitland** [comment]
> My implementation was using the latest version: 74.1.3

@krptodr This is a development version and not production ready, you should be using the latest stable version which is `73.1.130`. The next version will be based on `75`, there will be no `74` release (as per usual odd versions only)

> I also get the same error on the version that you found, that you did not reveive it: 73.1.130.

What do you mean? Are you seeing an exception with `73.1.130`? Please clarify.

> The SEHException class handles SEH errors that are thrown from unmanaged code, but that have not been mapped to another .NET Framework exception

As per https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.sehexception?view=netframework-4.8 the `SEHException` is very much a catch all exception.

> My implementation is very basic. I created a win32 winform project with the following code:

You stack trace references `kEvaluateJavascriptRequest` which if you aren't calling explicitly then it's probably a bug in `CEF` which will be resolved by upgrading to a newer version of `Chromium`.

**Comment by krptodr** [comment]
@amaitland by removing cefsharp as a reference, from the repository, I was able to find a working solution by using the nuget packages.

**Comment by chengang-hub** [comment]
I got error when  settings = new CefSettings();
:cef_string_wrappers.h   
return cef_string_utf8_to_utf16(data, length, s) ? true : false; 
System.Runtime.InteropServices.SEHException:

**Comment by brushli** [comment]
软件目录下，缺少chrome_elf.dl
当然有点不至少为什么会缺少它，我是通过示例的代码生成的相关文件发现的。
