### ISSUE TITLE
Cef.Shutdown() hangs if ChromiumWebBrowser is already disposed

### ISSUE THREAD

**Issue by peters** [cefsharp/CefSharp#820]
If you call the `ChromiumWebBrowser.Dispose()` method before calling `Cef.Shutdown()` the application will hang and is unable to shutdown. Removing the call to dispose fixes the issue.

This is observed on the latest `39.0.0-pre02` -pre release.

```cs
var browser = new ChromiumWebBrowser();
browser.Dispose();
Cef.Shutdown();
```

Ref: [ChromiumWebBrowser.cs](https://github.com/cefsharp/CefSharp/blob/b678ff168dbad98440e0111e7217a9db6894e17c/CefSharp.Wpf/ChromiumWebBrowser.cs#L373)
Ref: [Cef.h](https://github.com/cefsharp/CefSharp/blob/master/CefSharp.Core/Cef.h#L333)

There has to be some weirdness involved in relation to `AddDisposable/RemoveDisposable`.

/cc @amaitland

**Comment by amaitland** [comment]
@peters Can you try again with `master`? or the latest `CI` build? Some work was done recently to improve dispose, see #786

**Comment by peters** [comment]
@amaitland i'll try the latest CI build tomorrow :)

**Comment by amaitland** [comment]
'-pre03' is out, hopefully solves your issue.

**Comment by amaitland** [comment]
From what I can tell this has been resolved. Feel free to re-open if there's a problem :+1:

**Comment by peters** [comment]
@amaitland Upgraded to latest pre, the issue is still present. I don't have time for researching this right now, but i'll report back when i've identified the cause :)

**Comment by rassilon** [comment]
Well, could you help enlighten us about where the application is hanging on various threads?
See [#872 comment](https://github.com/cefsharp/CefSharp/issues/872#issuecomment-82505777) for an instance where accidentally creating COM objects on a CEF thread caused shutdown to hang for me.

Thanks,
Bill

**Comment by rassilon** [comment]
For posterity, note that this isn't an answer, but I ran into (but didn't have time to debug a similar issue).

I was adding an Unhandled Exception handler to my CefSharp WinForms application and it needs to have the app exit afterwards. 

Here's what I ended up with in Program.cs:Main:

            AppDomain.CurrentDomain.UnhandledException += CurrentDomain_UnhandledException;
            Application.ThreadException += Application_ThreadException;

(I was testing this logic by throwing an `InvalidOperationException` from a click handler of a menu bar item.)

Without the ThreadException handler I was still getting WinForm's Unhandled Exception dialog (Continue, Quit) kind of thing.

Here are my two handler functions:

        static void Application_ThreadException(object sender, ThreadExceptionEventArgs e)
        {
            CurrentDomain_UnhandledException(sender, new UnhandledExceptionEventArgs(e.Exception, false));
        }

        private static void CurrentDomain_UnhandledException(object sender, UnhandledExceptionEventArgs e)
        {
            Exception ex = null;
            if (e.ExceptionObject != null)
            {
                ex = e.ExceptionObject as Exception;
            }
            try
            {
                if (ex != null)
                {
                    Logger.Log.Exception("AppDomain_UnhandledException", ex);
                }
                // Ensure Application.Run exits cleanly to Main, so that the app won't
                // hang on shutdown.
                Application.Exit();
            }
            catch (Exception ex2)
            {
                Debug.Assert(false, "Exception in unhandled exception handler: " + ex2.ToString());
            }
        }

The trick here is to not get over anxious. I had initially just wanted to call Environment.Exit(1) directly here after calling Application.Exit(), but that caused the app shutdown to hang.

Bill

**Comment by Galen02** [comment]
I've been having this same hanging problem for a long.  I believe I've found what is at least a work-around to it.  I was delaying calling Cef.Initialize() until I needed the functionality.  As a result I was not calling Initialize in the main thread.  Now, when I call initialize in the main thread at the start of the application it no longer hangs.  I also call Cef.Shutdown() from the main thread when the application exits.  I hope this helps out.

**Comment by amaitland** [comment]
Closing this one for now, if someone can reproduce the problem with `master` then happy to reopen.

For reference I've updated the `Initailize/Shutdown` documentation as per the `API` see https://github.com/cefsharp/CefSharp/commit/42228561e4c401358398570385ef574407334fa4

http://magpcss.org/ceforum/apidocs3/projects/%28default%29/%28_globals%29.html#CefInitialize%28constCefMainArgs&,constCefSettings&,CefRefPtr%3CCefApp%3E,void*%29
http://magpcss.org/ceforum/apidocs3/projects/%28default%29/%28_globals%29.html#CefShutdown%28%29

**Comment by AndrewBragdon** [comment]
I had to call Cef.Shutdown() in order to fix this.  Why isn't this call made automatically by Cef?  I found it unintuitive that I needed to call Shutdown.  Ideally the library can hook in and shut itself down/garbage collect

**Comment by amaitland** [comment]
> I had to call Cef.Shutdown() in order to fix this. Why isn't this call made automatically by Cef? I found it unintuitive that I needed to call Shutdown.

https://github.com/cefsharp/CefSharp/wiki/General-Usage#initialize-and-shutdown

https://github.com/cefsharp/CefSharp/blob/cefsharp/55/CefSharp.WinForms/ChromiumWebBrowser.cs#L268
https://github.com/cefsharp/CefSharp/blob/cefsharp/55/CefSharp.Wpf/ChromiumWebBrowser.cs#L1533

@AndrewBragdon Before you make assertions about what does or doesn't happen perhaps you might wish to investigate further? An attempt is made to shutdown. If you have improvements or suggestions then how about making a contribution to the project rather than a non productive comment?

**Comment by kevinWu7** [comment]
I also meet this problem, I'm sure I  call the Cef.Initialize  and  Cef.shutdown in the UI thread
but my application  always hangs , I've encountered this problem in both versions 49 and 69.
       So , my solution is : set the CefSharpSettings.ShutdownOnExit=false after I called  Cef.Initialize 
then I add every ChromiumWebBrowser instance   into a List<ChromiumWebBrowser>,when the Application_Exit event is called, I will foreach the list, and close every ChromiumWebBrowser manually.
      Maybe it's not a good way, But it does work.
      If you are troubled by this problem, I hope I can help you.

**Comment by Snorvarg** [comment]
kevinWu7's solution works for me. I have a System.Windows.Forms.Form and by calling browser.Dispose(); (where browser is a ChromiumWebBrowser object) in the FormClosed event I could get the application to shut down properly.

**Comment by stargazer39** [comment]
I just wanted to put this here:
Don't set  `settings.CefCommandLineArgs.Add("--single-process");` flag too..  My Application just hangs when closing.
